chuippoint/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views
from informations import views as info_view
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', info_view.main_page, name="main_page"),
    path('posts/', include('posts.urls')),
    path('info/', include('informations.urls')),
    path('accounts/', include('accounts.urls')),
    # path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('search/', info_view.search, name='search'),
    re_path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    re_path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informations/urls.py
from django.urls import path
from . import views

app_name = "info"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:company_pk>/detail/', views.detail, name="detail"),
    path('gongos/', views.gongos, name="gongos"),
    path('gongos/<int:gongo_pk>/', views.gongo_detail, name="gongo_detail"),
    path('<int:gongo_pk>/bookmark/', views.bookmark, name="bookmark"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
   path('', views.index, name="index"),
   path('category/<int:category_pk>/', views.category_index, name="category_index"),
   path('create/', views.create, name='create'),
   path('<int:post_pk>/', views.detail, name='detail'),
   path('<int:post_pk>/update/', views.update, name='update'),
   path('<int:post_pk>/create/', views.comment_create, name="comment_create"),
   path('<int:post_pk>/update/<int:comment_pk>/', views.comment_update, name="comment_update"),
   path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
   path('<int:post_pk>/like/', views.like, name="like"),
   path('<int:post_pk>/like/<int:comment_pk>/', views.comment_like, name="comment_like"),
   # path('<int:post_pk>/reply/<int:comment_pk>/create/', views.reply_create, name="reply_create"),
   # path('<int:post_pk>/reply/<int:comment_pk>/detail/<int:reply_pk>/', views.reply_detail, name="reply_detail"),
]

informations/models.py
from django.db import models
from django.conf import settings


class Company(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    # logo = models.ImageField(blank=True)
    logo_path = models.CharField(max_length=200)
    employee = models.IntegerField()
    work_year = models.FloatField()


class Report(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    url = models.URLField(max_length=250)
    date = models.DateField()
    author = models.CharField(max_length=100)
    firm = models.CharField(max_length=250)


class Gongo(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    bookmark_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='bookmark_gongos')
    name = models.CharField(max_length=250)
    title = models.CharField(max_length=250)
    no = models.CharField(max_length=250)
    url = models.URLField(max_length=250)
    image = models.URLField(max_length=250)
    date = models.DateField()
    dday = models.IntegerField()
    # updated_at = models.DateTimeField(auto_now=True)


class Article(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    url = models.URLField(max_length=250)
    press = models.CharField(max_length=250)
    date = models.DateTimeField()


class Finance(models.Model):
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    capital = models.IntegerField()
    revenue = models.IntegerField()
    profit = models.IntegerField()
    debt = models.FloatField()
    year = models.IntegerField()

informations/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from urllib.request import urlopen
from urllib import parse
from bs4 import BeautifulSoup
import requests
import pandas as pd
from html_table_parser import parser_functions as parser
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
from datetime import date as datedate
import pytz
from django.utils.dateparse import parse_datetime
from django.http import JsonResponse
from pprint import pprint
import math
from .models import Company, Finance, Article, Gongo, Report
from posts.models import Post, Comment
import time
import random

# =================================================================================================================
# 기업 이름 : 기업 고유 번호 저장  => company : dictionary
def find_corp_num(find_name):
    new_date = 0
    result_corp_code = ''
    for country in root.iter("list"):
        if country.findtext("stock_code") != ' ' and country.findtext("corp_name") == find_name :
            if int(country.findtext("modify_date")) > new_date:
                new_date = int(country.findtext("modify_date"))
                result_corp_code = country.findtext("corp_code")
    return result_corp_code


def find_corp_stockcode(find_name):
    for country in root.iter("list"):
        if country.findtext("stock_code") != ' ' and country.findtext("corp_name") == find_name :
            return country.findtext("stock_code")

tree = ET.parse('CORPCODE.xml')
root = tree.getroot()
company_name = ['삼성전자','삼성에스디에스', '케이티','SK텔레콤','국민은행','NAVER', '우리은행','카카오','LG전자','LG유플러스','신한은행']
company = {}
company_stockcode = {}


for name in company_name: 
    # 기업 고유 번호 - dart 기업 정보
    company[name] = find_corp_num(name)
    # 기업 종목 코드 - 뉴스 크롤링
    company_stockcode[name] = find_corp_stockcode(name)
# =================================================================================================================
# =================================================================================================================

    # 직원 수
def load_data_employee(**kwargs):
    crtfc_key = 'b913de0ec72741e320cafa8e5fa18ac030699e38'
    corp_code = kwargs['corp_code']

    if kwargs['request'] == 'company':
         url = 'https://opendart.fss.or.kr/api/empSttus.json?crtfc_key='+crtfc_key+'&corp_code='+corp_code+'&bsns_year=2022&reprt_code=11011'

    r = requests.get(url)
    company_data = r.json()

    return company_data


    # 부채, 자산
def load_data_financial(**kwargs):
    crtfc_key = 'b913de0ec72741e320cafa8e5fa18ac030699e38'
    corp_code = kwargs['corp_code']

    if kwargs['request'] == 'company':
         url = 'https://opendart.fss.or.kr/api/fnlttSinglAcnt.json?crtfc_key='+crtfc_key+'&corp_code='+corp_code+'&bsns_year=2022&reprt_code=11011'

    r = requests.get(url)
    company_data = r.json()
    
    return company_data
# =================================================================================================================

def newsCrawler(company_code, page_num):
    url = 'https://finance.naver.com/item/news_news.naver?code='+company_code+'&page='+page_num
    html = urlopen(url).read()
    soup = BeautifulSoup(html, 'html.parser', from_encoding='cp949')
    time.sleep(random.randint(1, 4))
    title_td = soup.find_all("td", 'title')
    titles = []
    links = []
    # 제목, url
    for t in title_td:
        titles.append(t.get_text().strip('\n'))
        # /item/news_read.naver?article_id=0005082784&amp;office_id=014&amp;code=005930&amp;page=1&amp;sm=
        a = t.find('a', 'tit')['href'] 
        article_id = a[33:43]
        office_id = a[54:57]
        # print(article_id, office_id)
        link = 'https://n.news.naver.com/mnews/article/'+office_id+'/'+article_id
        links.append(link)
    # 신문사
    press = []
    press_td = soup.find_all('td', 'info')
    for p in press_td :
        press.append(p.get_text())
    # 발행일 
    date = []
    date_td = soup.find_all('td', 'date')
    for d in date_td :
        date.append(d.get_text())
    
    
    news_data = zip(titles, links, press, date)
    
    return news_data
# =================================================================================================================


    
# 프로젝트 메인페이지 랜더링
def main_page(request):
    companies = Company.objects.all()
    gongos = Gongo.objects.all().order_by('dday')[:12]
    articles = Article.objects.all().order_by('-date')[:10]

    context = {
        'companies': companies,
        'gongos': gongos,
        'articles': articles,
    }
    return render(request, 'index.html', context)

# 채용공고 메인페이지 랜더링
def gongos(request):
    return render(request, 'informations/gongo_index.html')

# 기업정보 메인페이지 랜더링
def index(request):
    if request.method ==  'POST':   
        # dart api 데이터 정리 및 저장
        for company_name, company_code in company.items():
            # 직원수        
            employee = load_data_employee(request = 'company', corp_code = company_code)
            sum_sm = 0
            sum_avrg = 0
            year_cnt = 0
            if employee and employee.get('list'):
                if len(employee.get('list')) > 2:
                    for list in employee.get('list'):
                        if list['fo_bbm'] == '성별합계':
                            sm = list['sm'].split(',')
                            sum_sm = ''
                            for s_str in sm:
                                sum_sm += s_str
                            sum_sm = int(sum_sm)
                            avrg_cnwk_sdytrn = list['avrg_cnwk_sdytrn']
                            year_cnt += 1
                            if '.' in avrg_cnwk_sdytrn:
                                sum_avrg += float(avrg_cnwk_sdytrn)
                            else:
                                save_year = ''
                                save_month = ''
                                year_flag = True
                                month_flag = True
                                for text in avrg_cnwk_sdytrn:
                                    if text.isdigit():
                                        if year_flag:
                                            save_year += text
                                        elif month_flag:
                                            save_month += text
                                    else:
                                        if text == '년':
                                            year_flag = False
                                        if text == '개':
                                            month_flag = False
                                if not save_year:
                                    save_year = 0
                                if not save_month:
                                    save_month = 0
                                sum_avrg += round(int(save_year) + float(int(save_month) / 12), 1)
                                        
                                    
                elif len(employee.get('list')) == 2:
                    for list in employee.get('list'):
                        sm = list['sm'].split(',')
                        sum_sm = ''
                        for s_str in sm:
                            sum_sm += s_str
                        sum_sm = int(sum_sm)
                        avrg_cnwk_sdytrn = list['avrg_cnwk_sdytrn']
                        year_cnt += 1
                        if '.' in avrg_cnwk_sdytrn:
                            sum_avrg += float(avrg_cnwk_sdytrn)
                        else:
                            save_year = ''
                            save_month = ''
                            year_flag = True
                            month_flag = True
                            for text in avrg_cnwk_sdytrn:
                                if text.isdigit():
                                    if year_flag:
                                        save_year += text
                                    elif month_flag:
                                        save_month += text
                                else:
                                    if text == '년':
                                        year_flag = False
                                    if text == '개':
                                        month_flag = False
                            if not save_year:
                                save_year = 0
                            if not save_month:
                                save_month = 0
                            sum_avrg += round(int(save_year) + float(int(save_month) / 12), 1)
            if year_cnt:
                sum_avrg = round(sum_avrg / year_cnt, 1)
            
            # 매출액, 당기순이익, 부채비율

            idx = 0
            financial = load_data_financial(request = 'company', corp_code = company_code)
            if financial and financial.get('list'):
                save_money = [0] * 3
                year = int(financial['list'][0].get('bsns_year'))
                capital = []
                data = {
                    year - 2: [0, 0, 0],
                    year - 1: [0, 0, 0],
                    year: [0, 0, 0],
                }
                for list in financial['list']:
                    if (list['account_nm'] == "매출액" or list['account_nm'] == "당기순이익") \
                        and list['fs_nm'] == "재무제표":
                        s_bfefrm = list['bfefrmtrm_amount'].split(',')
                        save_val = ''
                        for bfe_data in s_bfefrm:
                            save_val += bfe_data
                        data[year - 2][idx] = save_val[:7]
                        s_frmtrm = list['frmtrm_amount'].split(',')
                        save_val2 = ''
                        for ftm_data in s_frmtrm:
                            save_val2 += ftm_data
                        data[year - 1][idx] = save_val2[:7]
                        s_thstrm = list['thstrm_amount'].split(',')

informations/templates/informations/gongo_detail.html
{% extends "base.html" %}

{% block style %}
.header {
  font-family: 'NanumSquareExtraBold';
  margin-top: 1rem; 
  margin-bottom: 2rem; 
  background-color: #FCFAF3;
  color: #1B525C;
  height: 200px;
  padding: 0;
  border: 1px #FCFAF3 solid;
  border-radius: 1rem;
  display: flex;
  flex-direction: row;
}
iframe {
  width: 100%;
  height: 1000px;
}
.apply {
  width: 200px;
  margin-bottom: 2rem;
  background: #FFE76C;
}
{% endblock style %}


{% block content %}
<div class="container d-flex flex-column justify-content-center">
  <!-- header -->
  <div class="header col-12 rounded p-4 justify-content-around shadow-sm">
    <div class="d-flex p-3 row gx-3">
      <span class="fs-5">{{ gongo.name }}</span>
      <h2>{{ gongo.title }}</h2> 
      <span>~{{ gongo.date }}</span>
    </div>
    <div>
      <form id="likes-forms" data-gongo-id="{{ gongo.pk }}">
        {% csrf_token %}
        {% if request.user in gongo.bookmark_users.all %}
        <button type="submit" class="btn border-0">
          <i class="bi bi-bookmark-fill fs-3"></i>
        </button>
        {% else %}
        <button type="submit" class="btn border-0">
          <i class="bi bi-bookmark fs-3"></i>
        </button>
        {% endif %}
      </form>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <a href="https://www.jobkorea.co.kr/{{ gongo.url }}" class="btn btn-light apply btn-lg">지원하기</a>
  </div>
  
  <div class="iframe-div">
    <iframe src="https://m.jobkorea.co.kr/Recruit/GIReadDetailContentIframe/{{ gongo.no }}" frameborder="0" scrolling="yes"></iframe>
  </div>

</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  document.getElementById('gonggo').classList.add('active')
  const formTag = document.querySelector('#likes-forms')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  formTag.addEventListener('submit', function (event) {
    event.preventDefault()
      
    const gongoId = formTag.dataset.gongoId

    axios({
      url: `/info/${gongoId}/bookmark/`,
      method: 'post',
      headers: {'X-CSRFToken': csrftoken},
    })
      .then((response) => {
        const is_liked = response.data.is_liked
        const iTag = document.querySelector('#likes-forms > button > i')
        if (is_liked === true) {
          iTag.classList.remove('bi-bookmark')
          iTag.classList.add('bi-bookmark-fill')
        } else {
          iTag.classList.remove('bi-bookmark-fill')
          iTag.classList.add('bi-bookmark')
        }
      })
      .catch((error) => {
        console.log(error)
      })
  })
</script>
{% endblock content %}

informations/templates/informations/gongo_index.html
{% extends "base.html" %}


{% block style %}
header {
  font-family: 'NanumSquareExtraBold';
  margin-top: 1rem; 
  margin-bottom: 3rem; 
  background-color: #FCFAF3;
  color: #1B525C;
  height: 250px;
  padding: 0;
  border: 1px #FCFAF3 solid;
  border-radius: 1rem;
  display: flex;
  flex-direction: row;
}
.header-div {
  height: inherit;
  position: relative;
  z-index: 2;
  display: flex;
  justify-content: center;
  align-items: center;
  
  {% comment %} background-image: url('../../../static/img/dotted_pattern.avif'); {% endcomment %}
}
.header-img-div {
  position: relative;
  height: inherit;
  z-index: 1;
  width: 33.3%;
}
.header-img-div1 {
  position: relative;
  height: inherit;
  z-index: 1;
  width: 33.3%;
}
.header-img {
  height: inherit;
  width: 100%;
}
.header-img1 {
  height: 100%;
  width: 100%;
  position: absolute;
}
p {
  margin: 0;
}
.card {
  height: 200px;
}
.logo {
  height: 50px;
}
{% endblock style %}

{% block content %}
<div class="container">
    {% comment %} {% if request.user.is_authenticated and request.user.is_staff %} {% endcomment %}
    <div>
      <form action="{% url "info:gongos" %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>
    {% comment %} {% endif %} {% endcomment %}

    <!-- header -->
    <header class="position-relative d-flex flex-row justify-content-end shadow-sm">
    <div class="header-img-div">
      <img class='header-img1' src="../../../static/img/tryme_circle.png" alt="">
    </div>
    <div class="flex-grow-1 d-flex flex-column justify-content-center align-items-center">
      <div>
        <span class="display-6">
          공고
        </span>
        <span class="fs-2">
          찾기
        </span>
        <span class="fs-1">
          힘드시죠?
        </span>
      </div>
      <div>
        <span class="fs-2">
          옛다-
        </span>
        <span class="display-4">
          채용 정보
        </span>
      </div>
    </div>
    <div class="header-img-div">
      <img class='header-img1' src="../../../static/img/thinking_circle.png" alt="">
    </div>
  </header>

    <p class="fs-4">현재 {{ gongos|length }}개의 채용 진행 중</p>

    <!-- 공고 목록 -->
    <div class="row">
      {% for gongo in gongos %}
        <div class="col-6 col-lg-3 mb-2 g-2">
          <div class="card shadow-sm">
            <a href="{% url "info:gongo_detail" gongo.pk %}" class="link-dark text-decoration-none">
              <div class="card-body">
                <div class="d-flex justify-content-between">
                  <img class="logo" src="{{ gongo.image }}" alt="logo">
                  <form class="likes-forms" data-gongo-id="{{ gongo.pk }}">
                    {% csrf_token %}
                    {% if request.user in gongo.bookmark_users.all %}
                      <button type="submit" class="btn border-0" id="like-{{ gongo.pk }}">
                        <i class="bi bi-bookmark-fill fs-5"></i>
                      </button>
                    {% else %}
                    <button type="submit" class="btn border-0" id="like-{{ gongo.pk }}">
                      <i class="bi bi-bookmark fs-5"></i>
                    </button>
                    {% endif %}
                  </form>
                </div>
                <div class="mt-2">
                  <span class="fw-bold">{{ gongo.name }}</span>
                </div>
                <div class="mt-1">
                  <span>{{ gongo.title }}</span>
                </div>
                <div>
                  <span>D-{{ gongo.dday }}</span>
                </div>
              </div>
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  document.getElementById('gonggo').classList.add('active')
  const formTags = document.querySelectorAll('.likes-forms')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  formTags.forEach((formTag) => {
    formTag.addEventListener('click', function (event) {
      event.preventDefault()
      
      const gongoId = formTag.dataset.gongoId

      axios({
        url: `/info/${gongoId}/bookmark/`,
        method: 'post',
        headers: {'X-CSRFToken': csrftoken},
      })
        .then((response) => {
          const is_liked = response.data.is_liked
          const iTag = document.querySelector(`#like-${gongoId} > i`)
          if (is_liked === true) {
            iTag.classList.remove('bi-bookmark')
            iTag.classList.add('bi-bookmark-fill')
          } else {
            iTag.classList.remove('bi-bookmark-fill')
            iTag.classList.add('bi-bookmark')
          }
        })
        .catch((error) => {
          console.log(error)
        })
    })
  })
</script>
{% endblock content %}

informations/templates/informations/index.html
{% extends "base.html" %}
{% load static %}

{% comment %} {% block head %}
  <link rel="stylesheet" href="/informations/static/index.css">
{% endblock head %} {% endcomment %}

{% block style %}
header {
  font-family: 'NanumSquareExtraBold';
  margin-top: 1rem; 
  margin-bottom: 3rem; 
  background-color: #FCFAF3;
  color: #1B525C;
  height: 250px;
  padding: 0;
  border: 1px #FCFAF3 solid;
  border-radius: 1rem;
  display: flex;
  flex-direction: row;
}
.header-div {
  height: inherit;
  position: relative;
  z-index: 2;
  display: flex;
  justify-content: center;
  align-items: center;
  
  {% comment %} background-image: url('../../../static/img/dotted_pattern.avif'); {% endcomment %}
}
.header-img-div {
  position: relative;
  height: inherit;
  z-index: 1;
  width: 33.3%;
}
.header-img-div1 {
  position: relative;
  height: inherit;
  z-index: 1;
  width: 33.3%;
}
.header-img {
  height: inherit;
  width: 100%;
}
.header-img1 {
  height: 100%;
  width: 100%;
  position: absolute;
}
.list {
background: #8FBC8F;
padding: 0;
}
p {
margin: 0;
}
.card-grid-tag {
  height: 250px;
/* width:  */
}
.card-div {
  height: 100%;
  border-radius: 1em;

}
.card-body-tag {
  height: 50%;
  padding: 0.5rem;
}
.card-body-grid {
  height: 100%;
}
.card-img-tag {
  height: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
}
.card-text-div {
  display: flex;

}
.comp-name {
  height: inherit;
  display: flex;
  justify-content: center;
  align-items: center;
}
.comp-info {
  height: inherit;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: center;
}
.card-img-img {
  height: 100px;
}
.info-btn {
  background : #FED76D;
}
{% endblock style %}

{% block content %}
<div class="container">
  
  {% comment %} {% if request.user.is_authenticated and request.user.is_staff %} {% endcomment %}
  <div>
    <form action="{% url "info:index" %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Update</button>
    </form>
  </div>
  {% comment %} {% endif %} {% endcomment %}

  <!-- header -->
  <header class="position-relative d-flex flex-row justify-content-end shadow-sm">
    <div class="header-img-div">
      <img class='header-img1' src="../../../static/img/square_mulgunamu.png" alt="">
    </div>
    <div class="flex-grow-1 d-flex flex-column justify-content-center align-items-center">
      <div class="mb-1">
        <span class="display-5">
          기업
        </span>
        <span class="display-6">
          조사는?
        </span>
      </div>
      <div>
        <span class="display-2">
          컴포인트
        </span>
      </div>
    </div>
    <div class="header-img-div">
      <img class='header-img1' src="../../../static/img/painting_triangle.png" alt="">
    </div>
  </header>

  <!-- 기업 목록 -->
  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for company in companies %}
    <div class="col card-grid-tag ">
      <div class="card card-div mb-3 shadow-sm">
        <div class="card-img-tag">
          <a href="{% url "info:detail" company.pk %}" class="link-dark text-decoration-none">
            <img src="{{ company.logo_path }}" alt="기업 로고" class="card-img-top p-2 card-img-img">
          </a>
        </div>
        <div class="card-body-tag">
          <div class="row card-body-grid">
            <div class="col-3 offset-1 comp-name">
              <span class="fs-3 text-nowrap">{{ company.name }}</span>
            </div>
            <div class="col-6 offset-2 comp-info">
              <div>
                <span class="fs-5">현재 {{ company.gongo_set.all|length }} 개의 채용 진행 중</span>
              </div>
              <div>
                <a class="btn info-btn" href="{% url "info:detail" company.pk %}">정보 보러가기</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<script>
  document.getElementById('information').classList.add('active');
</script>
{% endblock content %}

informations/templates/informations/search.html
{% extends "base.html" %}
{% block style %}
a { 
    text-decoration: none;
}
a:hover { 
    text-decoration: underline;
}
.gongo_img { 
    height: 40px;
  }
.search-body {
    width: 1000px;
}
{% endblock style %}
{% block content %}
<div class="container m-3 d-flex justify-content-center">
    <div class="search-body">
    <div>
        <span class="fw-bold fs-3">검색 결과</span>
    </div>
    <hr>
    <div>
    <div>
        <span class="fw-bold fs-5">기업정보</span>
        <div class="border p-3 m-3 rounded">
            {% if search_companys %}
                {% for company in search_companys %}
                    <div class="m-0">
                        <a href="{% url "info:detail" company.pk %}">
                            <p class="fs-5 fw-bold">{{ company.name }}</p>
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                "{{ keyword }}에 대한 검색결과가 없습니다."
            {% endif %}
        </div>
    </div>
    <hr>
    <div>
        <div>
            <span class="fw-bold fs-5">채용 공고</span>
        </div>
        {% if search_gongos %} 
            {% for gongo in search_gongos %}
                <div class="border p-3 m-3 rounded">
                    <div class="m-0"><img src="{{ gongo.image }}" alt="" class="gongo_img m-0"> </div>
                    <div class="m-2"><span> <a href="{% url "info:gongo_detail" gongo.pk %}" class="text-dark">{{ gongo.title }}</a></span></div>
                    {{ gongo.date }}
                </div>
            {% endfor %}
            {% else %}
                <div class="border p-3 m-3 rounded">
                    "{{ keyword }}"에 대한 검색 결과가 없습니다.
                </div>
            {% endif %}

    </div>
    <hr>
    <div>
        <div>
            <span class="fw-bold fs-5">커뮤니티</span>
        </div>
        <div>
            {% if search_posts %}
                {% for post in search_posts %}
                    <div class="border p-3 m-3 rounded">
                        <div class="d-flex justify-content-between m-2">
                        <div class="m-0">
                            <span> <a href="{% url "posts:detail" post.pk%}" class="text-dark">{{ post.title }}</a></span>
                        </div>
                        <div class=m-0>
                            <i class="bi bi-heart"></i>
                            {{ post.like_users.all | length}}
                        </div>
                        </div>
                        <div class="p-2">
                            {% if post.created_string %}
                            <span>{{ post.created_string }}</span>
                            {% else %}
                            <span>{{ post.created_at | date:'m월 d일' }}</span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="border p-3 m-3 rounded">
                    "{{ keyword }}"에 대한 검색결과가 없습니다.
                </div>
            {% endif %}
        </div>
    </div>
    
</div>
</div>
</div>
{% endblock content %}