accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('password/<str:username>/', views.change_password, name='change_password'),
]

chuippoint/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views
from informations import views as info_view
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', info_view.main_page, name="main_page"),
    path('posts/', include('posts.urls')),
    path('info/', include('informations.urls')),
    path('accounts/', include('accounts.urls')),
    # path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('search/', info_view.search, name='search'),
    re_path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    re_path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informations/urls.py
from django.urls import path
from . import views

app_name = "info"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:company_pk>/detail/', views.detail, name="detail"),
    path('gongos/', views.gongos, name="gongos"),
    path('gongos/<int:gongo_pk>/', views.gongo_detail, name="gongo_detail"),
    path('<int:gongo_pk>/bookmark/', views.bookmark, name="bookmark"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
   path('', views.index, name="index"),
   path('category/<int:category_pk>/', views.category_index, name="category_index"),
   path('create/', views.create, name='create'),
   path('<int:post_pk>/', views.detail, name='detail'),
   path('<int:post_pk>/update/', views.update, name='update'),
   path('<int:post_pk>/create/', views.comment_create, name="comment_create"),
   path('<int:post_pk>/update/<int:comment_pk>/', views.comment_update, name="comment_update"),
   path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
   path('<int:post_pk>/like/', views.like, name="like"),
   path('<int:post_pk>/like/<int:comment_pk>/', views.comment_like, name="comment_like"),
   # path('<int:post_pk>/reply/<int:comment_pk>/create/', views.reply_create, name="reply_create"),
   # path('<int:post_pk>/reply/<int:comment_pk>/detail/<int:reply_pk>/', views.reply_detail, name="reply_detail"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=12, null=True)
    pass

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.forms import TextInput, EmailInput, PasswordInput
from django.utils.safestring import SafeString

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = '비밀번호'
        self.fields['password2'].label = '비밀번호 확인'
        self.fields['password1'].widget =  PasswordInput(attrs={
                'class':'form-control shadow-sm',
                'style' : 'width: 100%;',
                'placeholder':'최소 8자 이상 (숫자로만 이루어질 수 없습니다.)',
            })
        self.fields['password2'].widget = PasswordInput(attrs={
                'class':'form-control shadow-sm',
                'style' : 'width: 100%;',
                'placeholder': '비밀번호 확인'
            })

        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

    # def as_div(self):
    #     return SafeString(super().as_div().replace("<div>", "<div class='form-floating'>"))
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'nickname', 'email')
        labels = {
            'username':'아이디',
            'nickname':'닉네임',
            'email':'이메일',
        }
        help_texts = {
            'username':'',
            'password1':'test',
        }
        widgets = {
            'username': TextInput(attrs={
                'class':'form-control shadow-sm',
                'style' : 'width: 100%;',
                'placeholder':'4~15자 이내로 입력해주세요.',
            }),
            'nickname': TextInput(attrs={
                'class':'form-control shadow-sm',
                'style' : 'width: 100%;',
                'placeholder':'별명을 알파벳, 한글, 숫자로 20자 이하로 입력해주세요.'
            }),
            'email' : EmailInput(attrs={
                'class':'form-control shadow-sm',
                'style' : 'width: 100%;',
                'placeholder':'example@compoint.com'
            }),
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('nickname', 'email')

    nickname = forms.CharField(
        max_length=12,
        widget=forms.TextInput(attrs={
            'class': 'form-control  shadow-sm',
            'placeholder': 'nickname',
            'style' : 'width: 100%;',
            }),
        required=False)

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control  shadow-sm',
            'placeholder': 'email',
            'style' : 'width: 100%;',
            }),)
    
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['nickname'].label = '닉네임'
        self.fields['email'].label = '이메일'
        self.fields.pop('password')


class MyAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['username'].label = '아이디'
        self.fields['password'].label = '비밀번호'
        self.fields['username'].widget = forms.widgets.TextInput(attrs={
                'class': 'form-control  shadow-sm',
                'style' : 'width: 100%;',
            })
        self.fields['password'].widget = forms.widgets.PasswordInput(attrs={
                'class': 'form-control  shadow-sm',
                'style' : 'width: 100%;',
            })
        

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control  shadow-sm',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control  shadow-sm',
        })
        self.fields['new_password1'].help_text = ''

        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control  shadow-sm',
        })

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm, MyAuthenticationForm, CustomPasswordChangeForm
from django.contrib.auth import get_user_model

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('info:index')
    
    if request.method == 'POST':
        form = MyAuthenticationForm(request, request.POST)
        if form.is_valid():
            # 로그인 세션 생성
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'info:index')
    else :
        form = MyAuthenticationForm()
    context = {
        'form':form, 
    }
    return render(request,'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('info:index')


def signup(request):
    # 로그인한 사용자가 계정생성하는 것 막기
    if request.user.is_authenticated :
        return redirect('info:index')
    # 계정생성
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('info:index')
    else :
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def delete(request):
    request.user.delete() # 로그인한 유저 계정 삭제
    return redirect('info:index')    


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        # pw_form = CustomPasswordChangeForm(request.user, request.POST)
        # if form.is_valid() and pw_form.is_valid():
        if form.is_valid():
            form.save()
            # pw_form.save()
            return redirect('accounts:profile', request.user.username)
    else :
        form = CustomUserChangeForm(instance=request.user)
        # pw_form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
        # 'pw_form': pw_form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
def change_password(request, username):
    if request.method =='POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user= form.save()
            update_session_auth_hash(request, user)
            return redirect('info:index')
    else :
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html', context)



def profile(request, username):
    # 유저 정보
    user = get_user_model().objects.get(username=username)
    posts = user.post_set.all()
    comments = user.comment_set.all()
    gongos = user.bookmark_gongos.all()
    context = {
        'user':user,
        'posts':posts,
        'comments':comments,
        'gongos':gongos,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load static %}

{% block style %}
.logo_img {
  width: 100px;
}
div { 
  padding-top : 20px;
}

{% endblock style %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div>
      <div class="text-center">
        <img src="{% static "img/logo_mini.png" %}" class="logo_img" alt="" >
      </div>
      <div class="text-center">
        <h2>비밀번호 변경</h2>
        <p>
          COMPPOINT는 취업준비생과 직장인을 위한 사이트입니다
        </p>
        <hr>
      </div>
      <form action="{% url "accounts:change_password" request.user %}" method="POST" >
        {% csrf_token %}
        {{form.as_div}}
        <div class="d-flex justify-content-center mt-3">
          <input type="submit" class="btn btn-success" value="적용">
          <a class="btn btn-light ms-2" href="{% url "accounts:profile" request.user %}">취소</a>
        </div>
      </form>
    </div>
  </div>

  <script>
    document.getElementById('login').classList.add('active');
  </script>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block style %}
.logo_img {
  width: 100px;
}
div { 
  padding-top : 20px;
}

{% endblock style %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div>
      <div class="text-center">
        <img src="{% static "img/logo_mini.png" %}" class="logo_img" alt="" >
      </div>
      <div class="text-center">
        <h2>COMPPOINT에 오신 것을 환영합니다.</h2>
        <p>
          COMPPOINT는 취업준비생과 직장인을 위한 사이트입니다.
        </p>
        <hr>
      </div>
      <form action="{% url "accounts:login" %}" method="POST" >
        {% csrf_token %}
        {{form.as_div}}
        <div class="d-grid col-12">
          <input type="submit" class='btn btn-secondary btn-lg shadow' value="로그인">
        </div>
      </form>
      <div>
        <p>아직 회원이 아니신가요? <a href="{% url "accounts:signup"%}">회원가입</a></p>
    </div>
    </div>
  </div>

  <script>
    document.getElementById('login').classList.add('active');
  </script>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block style %}
.m_div { 
  margin-top : 30px;
}
.gongo_img { 
  height: 40px;
}
.container { 
  height: 1000px;
}
.com-div, .gong-div { 
  height : 700px;
}
a{
  text-decoration: none;
}
a:hover { 
  text-decoration :underline;
}
.btn-div {
  background-color: #FFE76C;
  color: #1C535C;
}
.active {
  
}
{% endblock style %}


{% block content %}
<div class="container m_div">
  <div class="m_div">
    <div class="row gx-5 m_div"> 
      <div class="col-3">
        <div class="m_div">
          <span class="fs-3">내 계정</span>
        </div> 
        <div class="list-group text-center m_div" id="list-tab"> 
          <a class="list-group-item active list-group-item-action " data-bs-toggle="list" href="#user_info"> 
            <span class="fs-6">회원 정보</span>
          </a> 
          <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#community_info"> 
            <span class="fs-6">커뮤니티 활동</span>
          </a> 
          <a class="list-group-item list-group-item-action" data-bs-toggle="list" href="#bookmark_info"> 
            <span class="fs-6">관심 공고</span>
          </a> 
        </div> 
      </div> 
      <div class="col-7 m_div"> 
        <div class="tab-content"> 
          <div class="tab-pane rounded active" id="user_info"> 
              <div class="">
                <span class="fs-3">회원 정보</span> 
              </div>
              <div class="border rounded p-3 shadow-sm d-flex flex-row">
                <div class="flex-grow-1">
                  <div class="m_div">
                    <span class="fs-4">닉네임 : {{ user.nickname }}</span>
                  </div>
                  <div class="m_div">
                    <span class="fs-4">아이디 : {{ user.username }}</span>
                  </div>
                  <div class="m_div mb-3">
                    <span class="fs-4">E-Mail : {{ user.email }}</span>
                  </div>
                </div>
                <div class="m_div flex-grow-1 d-flex flex-column justify-content-between align-items-end">
                  <div class="">
                    <a class="btn btn-outline-danger text-decoration-none" href="{% url "accounts:delete" %}">회원 탈퇴</a>
                  </div>
                  <div class="mb-3">
                    <a class="btn btn-outline-secondary text-decoration-none" href="{% url "accounts:update"%}">회원 정보 수정</a>
                  </div>
                </div>
              </div> 
          </div>
          <div class="tab-pane rounded" id="community_info"> 
            <div class="">
              <span class="fs-3">커뮤니티 활동</span> 
            </div>
            <div class="overflow-auto com-div">
              <div>
                <div class="border p-3 m-3 shadow-sm rounded me-4">
                {% if posts %}
                  {% for post in posts %}
                      <div class="d-flex justify-content-between m-2">
                        <div class="m-0">
                          <span> <a href="{% url "posts:detail" post.pk%}" class="text-dark">{{ post.title }}</a></span>
                        </div>
                        <div class=m-0>
                          <i class="bi bi-heart"></i>
                          {{ post.like_users.all | length}}
                        </div>
                      </div>
                      <div class="p-2">
                        {% if post.created_string %}
                        <span>{{ post.created_string }}</span>
                        {% else %}
                        <span>{{ post.created_at | date:'m월 d일' }}</span>
                        {% endif %}
                      </div>
                      {% endfor %}
                      {% else %}
                      <div>
                        <span class="fs-4">다양한 사람들과 게시판에서 소통해보세요!</span>
                      </div>
                      {% endif %}
                </div>
              </div> 
            </div>
          </div> 
          <div class="tab-pane rounded" id="bookmark_info"> 
            <div class="">
              <span class="fs-3">관심 공고</span> 
            </div>
            <div class="overflow-auto gong-div m_div">
              <div>
                {% if gongos %}
                  {% for gongo in gongos %}
                    <div class="border p-3 m_div shadow-sm rounded me-4">
                      <div class="m-0"><img src="{{ gongo.image }}" alt="" class="gongo_img m-0"> </div>
                      <div class="m-2"><span> <a href="{% url "info:gongo_detail" gongo.pk %}" class="text-dark">{{ gongo.title }}</a></span></div>
                      {{ gongo.date }}
                    </div>
                  {% endfor %}
                {% else %}
                <div class="border p-3 m_div shadow rounded">
                  <span class="fs-4">관심이 가는 공고를 추가해보세요!</span>
                  <br>
                  <br>
                  <a href="{% url "info:gongos" %}">채용 공고보러 가기</a>
                </div>
                {% endif %}
              </div> 
            </div>
          </div> 
        </div> 
      </div> 
    </div> 
  </div>
</div>

  
  
<script>
  
    document.getElementById('login').classList.add('active');

    function msg() { 
      alret("Hello world!")
    }
  </script>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block style %}

.logo_img {
  width: 100px;
}
div { 
  padding-top : 20px;
}

{% endblock style %}

{% block content %}
<div class="d-flex justify-content-center">
  <div>
    <div class="text-center">
      <img src="{% static "img/logo_mini.png" %}" class="logo_img" alt="" >
    </div>
    <div class="text-center">
      <h2>COMPOINT에 오신 것을 환영합니다.</h2>
      <p>
        COMPOINT는 취업준비생과 직장인을 위한 사이트입니다.
      </p>
      <hr>
    </div>
    <form action="{% url "accounts:signup" %}" method="POST" >
      {% csrf_token %}
      {{ form.as_div }}
      <div class="d-grid col-12">
        <input type="submit" class='btn btn-secondary btn-lg shadow' value="회원가입">
      </div>
    </form>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% load static %}

{% block style %}

.logo_img {
  width: 100px;
}
div { 
  padding-top : 20px;
}

{% endblock style %}

{% block content %}
<div class="d-flex justify-content-center">
  <div>
    <div class="text-center">
      <img src="{% static "img/logo_mini.png" %}" class="logo_img" alt="" >
    </div>
    <div class="text-center">
      <h2>회원정보 수정</h2>
      <p>
        COMPPOINT는 취업준비생과 직장인을 위한 사이트입니다.
      </p>
      <hr>
    </div>
    <form action="{% url "accounts:update"  %}" method="POST" >
      {% csrf_token %}
      {{form.as_div}}
      <div class="d-grid col-12">
        <div class="d-flex justify-content-center mt-3">
          <input type="submit" class="btn btn-success" value="적용">
          <a class="btn btn-light ms-2" href="{% url "accounts:profile" request.user %}">취소</a>
        </div>
        {% comment %} <input type="submit" class='btn btn-secondary btn-lg' value="회원가입"> {% endcomment %}
      </div>
    </form>
  </div>
</div>
{% endblock content %}
{% comment %} {% extends "base.html" %} {% endcomment %}
{% comment %} {% load static %} {% endcomment %}

{% comment %} {% block style %}
.logo_img {
  width: 100px;
}
div { 
  padding-top : 20px;
}
#id_password {
  display: none;
}
{% endblock style %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div>
      <div class="text-center">
        <img src="{% static "img/logo_mini.png" %}" class="logo_img" alt="" >
      </div>
      <div class="text-center">
        <h2>회원 정보 수정</h2>
        <p>
          회원 정보를 수정하는 페이지입니다.
        </p>
        <hr>
      </div>
      <form action="{% url "accounts:update" %}" method="POST" >
        {% csrf_token %}
        {{ form.as_div }} {% endcomment %}
        {% comment %} {{ pw_form.as_div }} {% endcomment %}
        {% comment %} <a class="btn btn-light ms-2" href="{% url "accounts:change_password" request.user %}">비밀번호 변경</a> {% endcomment %}
        {% comment %} <div class="d-flex justify-content-center mt-3">
          <input type="submit" class="btn btn-success" value="적용">
          <a class="btn btn-light ms-2" href="{% url "accounts:profile" request.user %}">취소</a>
        </div> {% endcomment %}
        {% comment %} <div class="d-grid col-12">
          <input type="submit" class='btn btn-secondary btn-lg' value="적용">
          <a class="btn btn-light ms-2" href="{% url "accounts:profile" request.user %}">취소</a>
        </div>
      </form>
    </div>
  </div>

  <script>
    document.getElementById('login').classList.add('active');
  </script>
{% endblock content %} {% endcomment %}