accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('password/<str:username>/', views.change_password, name='change_password'),
]

chuippoint/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views
from informations import views as info_view
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', info_view.main_page, name="main_page"),
    path('posts/', include('posts.urls')),
    path('info/', include('informations.urls')),
    path('accounts/', include('accounts.urls')),
    # path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('search/', info_view.search, name='search'),
    re_path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    re_path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informations/urls.py
from django.urls import path
from . import views

app_name = "info"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:company_pk>/detail/', views.detail, name="detail"),
    path('gongos/', views.gongos, name="gongos"),
    path('gongos/<int:gongo_pk>/', views.gongo_detail, name="gongo_detail"),
    path('<int:gongo_pk>/bookmark/', views.bookmark, name="bookmark"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
   path('', views.index, name="index"),
   path('category/<int:category_pk>/', views.category_index, name="category_index"),
   path('create/', views.create, name='create'),
   path('<int:post_pk>/', views.detail, name='detail'),
   path('<int:post_pk>/update/', views.update, name='update'),
   path('<int:post_pk>/create/', views.comment_create, name="comment_create"),
   path('<int:post_pk>/update/<int:comment_pk>/', views.comment_update, name="comment_update"),
   path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
   path('<int:post_pk>/like/', views.like, name="like"),
   path('<int:post_pk>/like/<int:comment_pk>/', views.comment_like, name="comment_like"),
   # path('<int:post_pk>/reply/<int:comment_pk>/create/', views.reply_create, name="reply_create"),
   # path('<int:post_pk>/reply/<int:comment_pk>/detail/<int:reply_pk>/', views.reply_detail, name="reply_detail"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COMPOINT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
    <!--
    font-family: 'NanumSquareLight';
    font-family: 'NanumSquare';
    font-family: 'NanumSquareBold';
    font-family: 'NanumSquareExtraBold';
    font-family: 'NanumSquareAcb';
    font-family: 'NanumSquareAceb';
    font-family: 'NanumSquareAcl';
    font-family: 'NanumSquareAcr';
    -->
    
    <style>
      html {
        height: 100%;
      }
      body {
        font-family: 'NanumSquare';
      }
      nav {
        background: #FFF;
        border-bottom: 1px lightgray solid;
      }
      .container {
        height: 80%;
      }
      {% block style %}{% endblock style %}
    </style>
    {% block head %}{% endblock head %}
</head>
<body>
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url "main_page"%}">
        <img src="{% static "img/logo.png" %}" alt="" width="30%">
      </a>
      <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link  text-nowrap" href="{% url "info:index"%}" id="information">기업정보</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-nowrap" href="{% url "info:gongos"%}" id="gonggo">채용정보</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-nowrap" href="{% url "posts:index" %}" id="post">커뮤니티</a>
            </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-nowrap" href="{% url "accounts:profile" request.user%}" id="profile">프로필</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-nowrap" href="{% url "accounts:logout"%}" id="logout">로그아웃</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link text-nowrap" href="{% url "accounts:login"%}" id="login">가입/로그인</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex" action="{% url "search" %}" >
            <div class="form-control me-2 text-nowrap">
              <label for="search"><i class="bi bi-search"></i></label>
              <input id="search" class="border border-0" type="search" name="q" placeholder="Search" aria-label="Search">
            </div>
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
  </nav>
  
  {% block content %}{% endblock content %}
  
  <hr>
  <footer class="p-3 text-body-secondary">
    <strong>문의</strong>
    <p>email: megar0829@gmail.com</p>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block style %}
{% endblock style %}

{% block content %}

<!-- 남은 날짜 D-day로 설정하기 -->
<!-- 뉴스 제목 길이 통일시키기 -->
<!-- footer 만들기 -->

<div class="container">
  <header>
    <img src="static/img/임시헤더.png/" alt="header" class="w-100">
  </header>

  <div class ="row row-cols-2 g-5">
    <div class="col">
      <!-- 최근 소식 -->
      <div>
        <h3>최근 소식</h3>
        <p>기업 정보에 더 많은 소식들이 있어요</p>
        <div class="card shadow-sm">
          <ul class="list-group list-group-flush">
            {% for article in articles %}
              <li class="list-group-item d-flex justify-content-between">
                <a href="{{ article.url }}" class="link-dark text-decoration-none">{{ article.title }}</a>
                <p class="text-muted">{{ article.date|date:"Y-m-d" }}</p>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <!-- 기업 리스트 -->
      <div class="mt-5">
        <h3>기업 리스트</h3>
        <p>한 번의 클릭으로 기업 조사가 가능해요</p>
        <div class="row row-cols-1 row-cols-lg-2">
          {% for company in companies %}
            <div class="col mb-3">
              <div class="card shadow-sm text-center">
                <a href="{% url "info:detail" company.pk %}" class="link-dark text-decoration-none">
                  <div class="card-body">
                    <img src="{{ company.logo_path }}" alt="기업 로고" height="33.5px">
                    {% comment %} <p>{{ company.name }}</p> {% endcomment %}
                  </div>
                </a>
              </div>
            </div>  
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="col" style="height: 100%;">
      
      <!-- 채용 공고 -->
      <div>
        <h3>채용 공고</h3>
        <div class="d-flex justify-content-between">
          <p>곧 채용이 마감되는 공고들이에요</p>
          <a href="{% url "info:gongos" %}" class="link-dark text-decoration-none"><p>더보기</p></a>
        </div>
        <div class="row row-cols-1 row-cols-lg-2 mb-3">
          {% for gongo in gongos %}
            <div class="col mb-3">
              <div class="card shadow-sm h-100">
                <a href="{% url "info:gongo_detail" gongo.pk %}" class="link-dark text-decoration-none">
                  <div class="card-body">
                    <img src="{{ gongo.image }}" alt="" style="width: 100px;">
                    <p>{{ gongo.title }}</p>
                    <p>{{ gongo.name }}</p>
                    <p>D-{{ gongo.dday }}</p>
                  </div>
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>

    </div>

  </div>
</div>
{% endblock content %}