chuippoint/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views
from informations import views as info_view
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', info_view.main_page, name="main_page"),
    path('posts/', include('posts.urls')),
    path('info/', include('informations.urls')),
    path('accounts/', include('accounts.urls')),
    # path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('search/', info_view.search, name='search'),
    re_path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    re_path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
   path('', views.index, name="index"),
   path('category/<int:category_pk>/', views.category_index, name="category_index"),
   path('create/', views.create, name='create'),
   path('<int:post_pk>/', views.detail, name='detail'),
   path('<int:post_pk>/update/', views.update, name='update'),
   path('<int:post_pk>/create/', views.comment_create, name="comment_create"),
   path('<int:post_pk>/update/<int:comment_pk>/', views.comment_update, name="comment_update"),
   path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
   path('<int:post_pk>/like/', views.like, name="like"),
   path('<int:post_pk>/like/<int:comment_pk>/', views.comment_like, name="comment_like"),
   # path('<int:post_pk>/reply/<int:comment_pk>/create/', views.reply_create, name="reply_create"),
   # path('<int:post_pk>/reply/<int:comment_pk>/detail/<int:reply_pk>/', views.reply_detail, name="reply_detail"),
]

posts/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta, timezone
# from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here. 
class Category(models.Model):
    name = models.CharField(max_length=100)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=30)
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(upload_to='images/',blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 댓글이 삭제돼도 대댓글은 삭제되지 않는다. 
    parent_comment = models.ForeignKey('self', on_delete = models.PROTECT, null=True)
    
    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False

posts/forms.py
from django import forms
from .models import Post, Comment
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        label_suffix='',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title form-control form-div',
                'placeholder': '제목을 입력해주세요.',
                'maxlength': 30,
            }
        )
    )
    content = forms.CharField(
        label='본문',
        label_suffix='',
        widget=CKEditorWidget(),
        error_messages={
            'required': '내용을 입력해 주세요.'
        }
    )

    # model 등록
    class Meta:
        model = Post
        exclude = ('user', 'like_users', 'category', 'image',)
        

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        label_suffix='',
        widget=forms.TextInput(attrs={
            'class': 'form-control ',
            'placeholder': '댓글을 작성해주세요.',
            'style' : 'width: 540px; height : 50px;',
            }),
    )
    class Meta:
        model = Comment
        fields = ('content',)
        

posts/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm

cat_lst = ['취업고민', '직장인고민', '이직고민', '자유게시판']

@require_http_methods(['GET', 'POST'])
def index(request):
    categories = Category.objects.all()
    if not categories:
        for cat in cat_lst:
            category = Category()
            category.name = cat
            category.save()

    category1 = Category.objects.get(pk=1)
    category2 = Category.objects.get(pk=2)
    category3 = Category.objects.get(pk=3)
    category4 = Category.objects.get(pk=4)

    posts1 = category1.posts.all()[:5]
    posts2 = category2.posts.all()[:5]
    posts3 = category3.posts.all()[:5]
    posts4 = category4.posts.all()[:5]

    posts = Post.objects.all()

    context = {
        'category1': category1,
        'category2': category2,
        'category3': category3,
        'category4': category4,
        'posts1': posts1,
        'posts2': posts2,
        'posts3': posts3,
        'posts4': posts4,

        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def category_index(request, category_pk):
    category = Category.objects.get(pk=category_pk)
    posts = category.posts.all()

    context = {
        'category': category,
        'posts': posts,
    }
    return render(request, 'posts/category_index.html', context)


@require_http_methods(['GET', 'POST'])
def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        post.delete()
        return redirect('posts:index')
    
    comment_form = CommentForm()
    comments = post.comment_set.all()

    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        category_name = request.POST.get('category')
        category = Category.objects.get(name=category_name)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.category = category
            form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    # if request.user == post.user:
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm(instance=post)
    # else:
    #     return redirect('posts:detail', post.pk)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def comment_create(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment_form.save()
            return redirect('posts:detail', post.pk)
    else:
        comment_form = CommentForm()
    comments = post.comment_set.all()
    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'posts/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def comment_update(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                form.save()
                return redirect('posts:detail', post_pk)
    
    post = get_object_or_404(Post, pk=post_pk)
    comments = Comment.object.all()    

    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts:detail.html', context)


@login_required
@require_http_methods(['POST'])
def comment_delete(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        return redirect('posts:detail', post_pk)


@login_required
@require_http_methods(['POST'])
def like(request, post_pk):
    post = Post.objects.get(pk=post_pk)

    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:detail', post_pk)


@login_required
@require_http_methods(['POST'])
def comment_like(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('posts:detail', post_pk)


# def reply_create(request, post_pk, comment_pk):
#     post = get_object_or_404(Post, pk=post_pk)
#     comment = get_object_or_404(Comment, pk=comment_pk)
#     reply_form = ReplyForm(request.POST)
    
#     if reply_form.is_valid():
#         reply = reply_form.save(commit=False)
#         reply.comment = comment
#         reply.user = request.user
#         reply_form.save()
#         return redirect('posts:detail', post_pk)
    
#     replies = Reply.objects.all()
    
#     context = {
#         'post': post,
#         'comment': comment,
#         'reply_form': reply_form,
#         'replies': replies,
#     }
#     return render(request, 'posts/detail.html', context)


# def reply_detail(request, post_pk, comment_pk, reply_pk):
#     pass

posts/templates/posts/category_index.html
{% extends "base.html" %}

{% block style %}
.header-div {
  margin-bottom: 3rem;
}
.cont-div {
  {% comment %} background-color: lightblue; {% endcomment %}
}
.cat-div {
  {% comment %} box-sizing: content-box; {% endcomment %}
}
.cat-div-cat {
  border: 1px #E5EAEE solid;
  border-radius: 1rem;
  height: 80px;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #E5EAEE;
  box-sizing: content-box
}
.cat-div-div {
  height: 90%;
}
.mid-div {
  height: 60px;
}
{% endblock style %}

{% block content %}
<div class = "container cont-div">
  <header class="cat-div-cat d-flex flex-row justify-content-center position-relative mt-4 mb-4">
    <div class="position-relative">
      <span class="fs-3">{{ category.name }} 게시판</span>
    </div>
  </header>
  <div class="position-relative mid-div">
    <div class="position-absolute top-0 end-0">
      <a class="btn btn-outline-secondary" href="{% url 'posts:create' %}">글 작성</a>
    </div>
  </div>
  <div class="cat-div col">
    <div class="cat-div-div mx-3 mt-1">
      {% for post in posts %}
      <div class="border-bottom border-secondary mb-3 pb-1">
        <div class="d-flex flex-row justify-content-between mb-1">
          <div>
            <span class="fs-5">{{ post.user.nickname }} </span>
          </div>
          <div>
            {% if post.created_string %}
            <span>{{ post.created_string }}</span>
            {% else %}
            <span>{{ post.created_at | date:'m월 d일' }}</span>
            {% endif %}
            <span>
              <i class="bi bi-heart"></i>
              {{ post.like_users.all | length}}
            </span>
          </div>
        </div>
        <div>
          <div>
            <a class="text-decoration-none link-dark" href="{% url "posts:detail" post.pk %}">
              <span class="fs-5">{{ post.title }}</span>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<script>
  document.getElementById('post').classList.add('active');
</script>
{% endblock content %}

posts/templates/posts/create.html
{% extends "base.html" %}

{% block style %}
.con-div {
  width: 800px;
}
.form-div {
  width: 100%;
  height: 50px;
}
.form-text {
  width: 100%;
}
.btn-upload {
  background-color: #FFE76C;
  color: #1C535C;
}
.btn-cancle {
  {% comment %} background-color: #FFE76C;
  color: #1C535C; {% endcomment %}
}
{% endblock style %}

{% block content %}
  <div class="container con-div">
    <h2 class="mt-3 mb-2">함께 할 때 더 즐거운 순간</h2>
    <h6 class="mb-4">{{ request.user.nickname }}님 Compoint에서 다양한 사람을 만나고 생각의 폭을 넓혀보세요.</h6>
    <form action="{% url "posts:create" %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-4">
        <div class="mb-3">
          <label for="cat" class="fs-6">토픽</label>
        </div>
        <div class="">
          <select name="category" id="cat" class="form-control form-div">
            <option value="">토픽을 선택해주세요.</option>
            <option value="취업고민">취업고민</option>
            <option value="직장인고민">직장인고민</option>
            <option value="이직고민">이직고민</option>
            <option value="자유게시판">자유게시판</option>
          </select>
        </div>
      </div>
      {{ form.media }}
      
      <div class="mb-4">
        <div class="mb-2">
          <span class="fs-6">
            {{ form.title.label }}
          </span>
        </div>
        <div class="">
          {{ form.title }}
        </div>
      </div>

      <div class="mb-4">
        <div class="mb-2">
          <span class="fs-6">
            {{ form.content.label }}
          </span>
        </div>
        <div class="form-text">
          {{ form.content }}
        </div>
      </div>

      <hr>
      <div class="d-flex flex-row justify-content-end">
        <div class="mx-2">
          <input class="btn btn-upload" type="submit" value="등록">
        </div>
        <div class="me-3">
          <a class="btn btn-cancle" href="{% url 'posts:index' %}">취소</a>
        </div>
      </div>
    </form>
  </div>
<script>
  document.getElementById('post').classList.add('active');

  const ckDiv = document.querySelector('.django-ckeditor-widget')
  ckTag.classList.add('rounded')

  const ckTag = document.querySelector('.cke_inner')
  ckTag.classList.add('form-control')
</script>
{% endblock content %}

posts/templates/posts/detail.html
{% extends "base.html" %}

{% block style %}
.cat-div {
  font-family: 'NanumSquareBold';
}
.like_btn {
  background-color : #FED76D;
}
.comment-btn {
  background-color : #FED76D;
}
{% endblock style %}

{% block content %}
  <div class="container">
    <div class="cat-div my-3">
      <span class="cat-span fs-5">카테고리 : {{ post.category.name }}</span>
    </div>
    <hr>
    <strong class="fs-4">{{ post.title }}</strong>
    <div class="my-3">
      <span class="">{{ post.user.nickname }} |</span>
      <span>{{ post.created_at | date:'Y.m.d H:i'}}</span>
    </div>
    <hr>
    {% if post.image %}
      <img src="{{ post.image.url }}" alt="#">
    {% endif %}
    <p>{{ post.content |safe | linebreaksbr }}</p>

    <hr>
    <div class="d-flex justify-content-end">
      <div class="me-2">
        <form action="{% url "posts:like" post.pk %}" method="POST">
          {% csrf_token %}
          {% if request.user in post.like_users.all %}
            <button type="submit" class="btn btn-light ms-3 like_btn">좋아요 취소</button>
          {% else %}  
            <button type="submit" class="btn btn-light ms-3 like_btn">좋아요</button>
          {% endif %}
        </form>
      </div>
      <a class="btn btn-light me-2" href="{% url "posts:index" %}">뒤로가기</a>
      {% if request.user.username == post.user.username %}
      <a class="btn btn-light me-2" href="{% url "posts:update" post.pk %}">수정</a>
      <form action="{% url "posts:detail" post.pk %}" method="POST">
        {% csrf_token %}
        <input class="btn btn-light" type="submit" value="삭제">
      </form>
      {% endif %}
    </div>
    <hr>
    <div class="border rounded">
      <form action="{% url "posts:comment_create" post.pk %}" method="POST" class="m-2 d-flex justify-content-between">
        {% csrf_token %}
        {{ comment_form.as_div }}
        <input type="submit" value="댓글 작성" class="btn comment-btn">
      </form>
    
    </div>
    <hr>
    {% if comments %}
      {% for comment in comments %}
      <div class="border rounded m-2">
        <div class="d-flex justify-content-between">
          <div class="m-2">
            <span class="me-2">{{ comment.user.nickname }}</span>|
            <span class="ms-2">
              {% if comment.created_string %}
              <span>{{ comment.created_string }}</span>
              {% else %}
              <span>{{ comment.created_at | date:'Y.m.d H:i' }}</span>
              {% endif %}
            </span> 
          </div>
          <div>
            <form action="{% url "posts:comment_like" post.pk comment.pk %}" method="POST">
              {% csrf_token %}
                {% if request.user in comment.like_users.all %}
                  <button type="submit" class="btn ms-3"><i class="bi bi-heart-fill"></i></button>
                {% else %}  
                  <button type="submit" class="btn ms-3"><i class="bi bi-heart" type="submit"></i></button>
                {% endif %}
                <span class="m-2">{{ comment.like_users.all | length }}</span>
            </form>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <div class="m-2">
            <span> {{ comment.content }}</span>
          </div>
          <div>
          {% if request.user == comment.user %}
              <form action = "{% url "posts:comment_delete" post.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제" class="btn btn ms-3" class="m-2">
              </form>
          {% endif %}
          </div>
        </div>

    </div>
      {% endfor %}
    {% else %}
    <div class="border rounded mt-5 m-2 p-5 text-center">
      아직 댓글이 없습니다. 첫번째 댓글의 주인공이 되어주세요!
    </div>
    {% endif %}
<script>
  document.getElementById('post').classList.add('active');
</script>
{% endblock content %}

posts/templates/posts/index.html
{% extends "base.html" %}

{% block style %}
header {
  font-family: 'NanumSquareExtraBold';
  margin-top: 1rem; 
  margin-bottom: 3rem; 
  background-color: #FCFAF3;
  color: #1B525C;
  height: 250px;
  padding: 0;
  border: 1px #FCFAF3 solid;
  border-radius: 1rem;
  display: flex;
  flex-direction: row;
}
.header-div {
  height: inherit;
  position: relative;
  z-index: 2;
  display: flex;
  justify-content: center;
  align-items: center;
  
  {% comment %} background-image: url('../../../static/img/dotted_pattern.avif'); {% endcomment %}
}
.header-img-div {
  position: relative;
  height: inherit;
  z-index: 1;
  width: 33.3%;
}
.header-img-div1 {
  position: relative;
  height: inherit;
  z-index: 1;
  width: 33.3%;
}
.header-img {
  height: inherit;
  width: 100%;
}
.header-img1 {
  height: 100%;
  width: 100%;
  position: absolute;
}
.cont-div {
  {% comment %} background-color: lightblue; {% endcomment %}
}
.cat-div {
  {% comment %} box-sizing: content-box; {% endcomment %}
}
.cat-div-cat {
  border: 1px #FED76D solid;
  border-radius: 0.5rem;
  height: 10%;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #FED76D;
  padding-left: 1rem;
  padding-right: 1rem;
  box-sizing: content-box;
  font-family: 'NanumSquareBold';
}
.cat-div-div {
  height: 90%;
}
{% endblock style %}

{% block content %}
<div class="container">
  <!-- header -->
  <header class="position-relative d-flex flex-row justify-content-end shadow-sm">
    <div class="flex-grow-1 d-flex flex-column justify-content-center align-items-center">
      <div>
        <span class="display-6">
          다양한 사람들과
        </span>
        <span class="display-5">
          소통하는
        </span>
      </div>
      <div>
        <span class="display-2">
          커뮤니티
        </span>
        <span class="display-6">
          공간입니다
        </span>
      </div>
    </div>
    <div class="header-img-div me-4">
      <img class='header-img1' src="../../../static/img/three.png" alt="">
    </div>
  </header>
  <div class="d-flex flex-row justify-content-end mb-4">
    <div>
      <a class="btn btn-outline-secondary" href="{% url 'posts:create' %}">글 작성</a>
    </div>
  </div>

  <div class = "cont-div row row-cols-1 row-cols-md-2 g-4">
    <div class="cat-div col">
      <div class="cat-div-cat mb-3 shadow-sm">
        <a class="text-decoration-none link-dark" href="{% url "posts:category_index" category1.pk %}">
          <span class="fs-4">{{ category1.name }}</span>
        </a>
      </div>
      <div class="cat-div-div mx-2 mt-1">
        {% for post1 in posts1 %}
        <div class="border-bottom border-secondary mb-3 pb-1">
          <div class="d-flex flex-row justify-content-between mb-1">
            <div>
              <span class="fs-5">{{ post1.user.nickname }} </span>
            </div>
            <div>
              {% if post1.created_string %}
              <span>{{ post1.created_string }}</span>
              {% else %}
              <span>{{ post1.created_at | date:'m월 d일' }}</span>
              {% endif %}
              <span>
                <i class="bi bi-heart"></i>
                {{ post1.like_users.all | length}}
              </span>
            </div>
          </div>
          <div>
            <div>
              <a class="text-decoration-none link-dark" href="{% url "posts:detail" post1.pk %}">
                <span class="fs-5">{{ post1.title }}</span>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="cat-div col">
      <div class="cat-div-cat mb-3 shadow-sm">
        <a class="text-decoration-none link-dark" href="{% url "posts:category_index" category2.pk %}">
          <span class="fs-4">{{ category2.name }}</span>
        </a>      
      </div>
      <div class="cat-div-div mx-2 mt-1">
        {% for post2 in posts2 %}
        <div class="border-bottom border-secondary mb-3 pb-1">
          <div class="d-flex flex-row justify-content-between mb-1">
            <div>
              <span class="fs-5">{{ post2.user.nickname }} </span>
            </div>
            <div>
              {% if post2.created_string %}
              <span>{{ post2.created_string }}</span>
              {% else %}
              <span>{{ post2.created_at | date:'m월 d일' }}</span>
              {% endif %}
              <span>
                <i class="bi bi-heart"></i>
                {{ post2.like_users.all | length}}
              </span>
            </div>
          </div>
          <div>
            <div>
              <a class="text-decoration-none link-dark" href="{% url "posts:detail" post2.pk %}">
                <span class="fs-5">{{ post2.title }}</span>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="cat-div col mt-5">
      <div class="cat-div-cat mb-3 shadow-sm">
        <a class="text-decoration-none link-dark" href="{% url "posts:category_index" category3.pk %}">
          <span class="fs-4">{{ category3.name }}</span>
        </a>      
      </div>
      <div class="cat-div-div mx-2 mt-1">
        {% for post3 in posts3 %}
        <div class="border-bottom border-secondary mb-3 pb-1">
          <div class="d-flex flex-row justify-content-between mb-1">
            <div>
              <span class="fs-5">{{ post3.user.nickname }} </span>
            </div>
            <div>
              {% if post3.created_string %}
              <span>{{ post3.created_string }}</span>
              {% else %}
              <span>{{ post3.created_at | date:'m월 d일' }}</span>
              {% endif %}
              <span>
                <i class="bi bi-heart"></i>
                {{ post3.like_users.all | length}}
              </span>
            </div>
          </div>
          <div>
            <div>
              <a class="text-decoration-none link-dark" href="{% url "posts:detail" post3.pk %}">
                <span class="fs-5">{{ post3.title }}</span>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="cat-div col mt-5">
      <div class="cat-div-cat mb-3 shadow-sm">
        <a class="text-decoration-none link-dark" href="{% url "posts:category_index" category4.pk %}">
          <span class="fs-4">{{ category4.name }}</span>
        </a>      
      </div>
      <div class="cat-div-div mx-2 mt-1">
        {% for post4 in posts4 %}
        <div class="border-bottom border-secondary mb-3 pb-1">
          <div class="d-flex flex-row justify-content-between mb-1">
            <div>
              <span class="fs-5">{{ post4.user.nickname }} </span>
            </div>
            <div>
              {% if post4.created_string %}
              <span>{{ post4.created_string }}</span>
              {% else %}
              <span>{{ post4.created_at | date:'m월 d일' }}</span>
              {% endif %}
              <span>
                <i class="bi bi-heart"></i>
                {{ post4.like_users.all | length}}
              </span>
            </div>
          </div>
          <div>
            <div>
              <a class="text-decoration-none link-dark" href="{% url "posts:detail" post4.pk %}">
                <span class="fs-5">{{ post4.title }}</span>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>   
  </div>  
</div>
  

  <script>
  document.getElementById('post').classList.add('active');
</script>
{% endblock content %}

posts/templates/posts/update.html
{% extends "base.html" %}

{% block style %}
.con-div {
  width: 800px;
}
.form-div {
  width: 100%;
  height: 50px;
}
.form-text {
  width: 100%;
}
.btn-upload {
  background-color: #FFE76C;
  color: #1C535C;
}
.btn-cancle {
  {% comment %} background-color: #FFE76C;
  color: #1C535C; {% endcomment %}
}
{% endblock style %}

{% block content %}
  <div class="container con-div">
    <div class="d-flex flex-row">
      <div class="d-flex flex-column justify-content-center">
        <span class="mt-3 mb-2 fs-2">함께 할 때 더 즐거운 순간</span>
        <span class="mb-4 fs-6">{{ request.user.nickname }}님 Compoint에서 다양한 사람을 만나고 생각의 폭을 넓혀보세요.</span>
      </div>
      <div class="mx-5 flex-grow-1 d-flex flex-row justify-content-end align-items-center">
        <span class="form-control">{{ post.category.name }} 게시판</span>
      </div>
    </div>
    <form action="{% url "posts:update" post.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}
      
      <div class="mb-4">
        <div class="mb-2">
          <span class="fs-6">
            {{ form.title.label }}
          </span>
        </div>
        <div class="">
          {{ form.title }}
        </div>
      </div>

      <div class="mb-4">
        <div class="mb-2">
          <span class="fs-6">
            {{ form.content.label }}
          </span>
        </div>
        <div class="form-text">
          {{ form.content }}
        </div>
      </div>

      <hr>
      <div class="d-flex flex-row justify-content-end">
        <div class="mx-2">
          <input class="btn btn-upload" type="submit" value="수정">
        </div>
        <div class="me-3">
          <a class="btn btn-cancle" href="{% url 'posts:index' %}">취소</a>
        </div>
      </div>
    </form>
  </div>
<script>
  document.getElementById('post').classList.add('active');

  const ckDiv = document.querySelector('.django-ckeditor-widget')
  ckTag.classList.add('rounded')

  const ckTag = document.querySelector('.cke_inner')
  ckTag.classList.add('form-control')
</script>
{% endblock content %}